# Generated by Django 5.1.6 on 2025-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='report',
        ),
        migrations.DeleteModel(
            name='data',
        ),
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='report',
            name='Cordinates',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='forced_sale_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='report',
            name='inspection_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='report',
            name='land_size',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='report',
            name='mortgage_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reserve_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='report',
            name='title_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
